# Sample hello world tomcat web application as a docker image.
# Base image is from the official tomcat docker hub repository(https://hub.docker.com/_/tomcat/). 
FROM tomcat:9.0-jre8-alpine
# copy the sample web application
COPY DemoApp.war /usr/local/tomcat/webapps/
